### PR TITLE
Made email indexing case-insensitive for user and account models

### LINKED ISSUE #234: [BUG] Case sensitivity for accounts - investigate
## Description

A brief description of the bug

## Reproduction Steps

Steps to reproduce the bug

## Expected Behavior

Description of the expected behavior

### PR DESCRIPTION
**Pull request by aeluro1**
Case-insensitive email indexing

Issue Number(s): #261

### CODE REVIEW

File: web/db/actions/User.ts [hunk 1]
```diff
@@ -123,7 +129,9 @@ async function searchUsers(
   session?: ClientSession
 ): Promise<IUser[]> {
   const filter = createFilterQuery(searchParams);
-  return await User.find(filter, { _id: 0, __v: 0 }, { session }).exec();
+  return await User.find(filter, { _id: 0, __v: 0 }, { session })
+    .collation({ locale: "en", strength: 2 })
```
Comment (katsukixyz) [inline web/db/actions/User.ts]: Does this query need collation?

**Comment by aeluro1** [comment]
You're right, it's not needed. Just pushed a quick update!

**Review by katsukixyz — APPROVED** [review]
LGTM! Nice work on the test
